### ISSUE TITLE
Add "type = module" in the .info file.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/video_filter#1]
From the [generated PACKAGING_ERROR_LOG.txt](https://github.com/backdrop-contrib/video_filter/releases/download/1.x-3.0/PACKAGING_ERROR_LOG.txt):

```
Reported errors:
The project node could not be created on BackdropCMS.org because no "type" property was specified in the project .info file.
```

**Comment by herbdool** [comment]
is that all it requires? I noticed some people were also adding version = VERSION or version = BACKDROP_VERSION

**Comment by klonos** [comment]
Not sure, I just noticed the addition for support of the `type = module` lately and that's what the error in the log points to.

BTW, you might also want to do the same for the rest of the projects you maintain. Let me know if you actually want me to file separate issues in their queues if that helps you keep track of things.
