### ISSUE TITLE
Deprecated function: strpos(): Passing null to parameter #1

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/video_filter#18]
Full message on PHP 8.1:
```
Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in theme_help() (line 2483 of ...core/includes/theme.inc).
```

This is caused by [theme('help')](https://github.com/backdrop-contrib/video_filter/blob/1.x-3.x/video_filter.module#L513) without any variables passed. Not sure, why that's there, anyway. It seems to be ancient code.

Maybe just remove that line?

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop-contrib/video_filter/pull/19) is available now.

**Comment by herbdool** [comment]
@indigoxela thanks! I don't know why it's there either - maybe something I removed and I don't remember.

**Comment by indigoxela** [comment]
> I don't know why it's there either

My suspicion is, that this is some leftover code from the D6 to D7 migration (very old code). :shrug:
