### ISSUE TITLE
Video filter settings lost everytime the filter form gets saved without adapting video filter

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/video_filter#22]
To reproduce:

- Enable the filter on some format
- Configure, for example with different default dimensions
- Save the form
- Inspect config - configured values are there
- Open the form again (/admin/config/content/formats/filtered_html)
- Do *not* adapt anything in video filter settings
- Save the form
- Inspect config - everything re video_filter is back to defaults, all adaptions lost

Reproducible 100% on PHP 8.2 - didn't try different PHP versions, yet, but I don't think, that's actually relevant.
Testing on latest core dev, but discovered the problem on Backdrop 1.27.1.
Video filter module 1.x-3.5.0 (didn't realize the problem earlier, but it was probably there since it was ported).

**Comment by indigoxela** [comment]
Oops, never mind, it's a core bug.

The url filter's also affected. I'll open an issue in the core queue.

**Comment by indigoxela** [comment]
@herbdool as this module's heavily affected by the linked core bug, you might be interested in testing the available fix [over there](https://github.com/backdrop/backdrop-issues/issues/6431). :wink:

**Comment by herbdool** [comment]
Core bug fixed.
