### ISSUE TITLE
Function _video_filter_instructions() doesn't account for disabled filter

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/video_filter#32]
That function builds the instructions fieldset by looping over all formats and grabbing the enabled codecs.

However, it doesn't account for *disabled* status of that filter in a format, which leads to all codecs showing up in instructions, if one of the formats doesn't have the video filter enabled at all.

That's not new, only caused me some head scratching today with the latest update. :wink:

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop-contrib/video_filter/pull/33) that adds the check.

**Comment by indigoxela** [comment]
@herbdool seems like you missed this bug report an PR. :wink:

**Comment by herbdool** [comment]
Thanks @indigoxela
